module.exports = {
    FULL: 'full',
    NEED_WAIT: 'need wait',
    NEW_MESSAGE: 'new message',
    USER_LEFT: 'user left',
    USER_LOGIN: 'login',
    USER_JOINED: 'user joined',
    GAME_READY: 'game ready',
    ROLE_NOTICE: 'role notice',
    MAFIA_NOTICE: 'mafia notice',
    BECOME_NIGHT: 'become night',
    BECOME_DAY: 'become day',
    MAFIA_WIN: 'mafia win',
    CITIZEN_WIN: 'citizen win',
    GUESS_OK: 'guess ok',
    LAST_SPEAK: 'last speak',
    THUMB_UPDOWN: 'thumb updown',
    POINT_MAFIA: 'point mafia',
    NOTICE_DEAD: 'notice dead',
    NOTICE_ALIVE: 'notice alive',
    GUESS_FAIL: 'guess fail',
    STATUS: 'status',
    NOT_ALLOWED: 'not allowed',
    POLICE_CONFIRM: 'police confirm',
    HELP_MANUAL: 'help  manual',
    USER_NON_EXIST: 'user nonexist',
    VOTE_FEEDBACK: 'vote feedback',
    KILL_FEEDBACK: 'kill feedback',
    INVALID_VOTE: 'invalid vote',
    INVALID_KILL: 'invalid kill'
};
